#!/usr/bin/env python3
"""Derive G9 C1 V8 from exact V7; only frozen Amendment09 build/evidence fixes."""
import difflib
import hashlib
import json
from pathlib import Path
import shutil
import sys

V7_BLOB = 'ada4af1131806c48bdc8556341e12320829a33d3'


def git_blob(raw: bytes) -> str:
    return hashlib.sha1(b'blob ' + str(len(raw)).encode() + b'\0' + raw).hexdigest()


REPLACEMENTS = [
    (
        'VFILE="$GEN/rocketchip.DefaultConfigWithRVFIMonitors.v"\n',
        'VFILE="$GEN/freechips.rocketchip.system.DefaultConfigWithRVFIMonitors.v"\n',
    ),
    (
        'SRAM="$GEN/rocketchip.DefaultConfigWithRVFIMonitors.behav_srams.v"\n',
        'SRAM="$GEN/freechips.rocketchip.system.DefaultConfigWithRVFIMonitors.behav_srams.v"\n',
    ),
    (
        'test -s "$VFILE"\ntest -s "$SRAM"\n\n# Reproduce the successor riscv-formal Rocket->RVFI IL transformation.\n',
        'test -s "$VFILE"\ntest -s "$SRAM"\n\n'
        '# Preserve exact generated bytes for independent audit; Yosys still reads historical source path.\n'
        'sha256sum "$VFILE" "$SRAM" > "$OUT/generated-uncompressed-sha256.txt"\n'
        'wc -c "$VFILE" "$SRAM" > "$OUT/generated-uncompressed-sizes.txt"\n'
        'gzip -c -9 "$VFILE" > "$OUT/generated-rocket-verilog.v.gz"\n'
        'gzip -c -9 "$SRAM" > "$OUT/generated-behavioral-sram.v.gz"\n'
        'sha256sum "$OUT/generated-rocket-verilog.v.gz" "$OUT/generated-behavioral-sram.v.gz" > "$OUT/generated-compressed-sha256.txt"\n'
        '\n# Reproduce the successor riscv-formal Rocket->RVFI IL transformation.\n',
    ),
]


def main():
    if len(sys.argv) != 4:
        raise SystemExit('usage: g9_c1_amendment09_patch.py V7_RUNNER V8_RUNNER DIFF_FILE')
    src, dst, diff = map(Path, sys.argv[1:])
    if len({src.resolve(), dst.resolve(), diff.resolve()}) != 3:
        raise SystemExit('SOURCE_AND_OUTPUT_MUST_BE_DISTINCT')
    old_bytes = src.read_bytes()
    if git_blob(old_bytes) != V7_BLOB:
        raise SystemExit('FROZEN_V7_BLOB_MISMATCH')
    old = old_bytes.decode('utf-8')
    new = old
    for i, (before, after) in enumerate(REPLACEMENTS, 1):
        count = new.count(before)
        if count != 1:
            raise SystemExit(f'ANCHOR_{i}_COUNT_{count}')
        new = new.replace(before, after, 1)
    if new == old or not new.endswith('\n') or dst.exists() or diff.exists():
        raise SystemExit('DERIVATION_OR_DESTINATION_INVARIANT_FAILED')
    raw = new.encode('utf-8')
    patch = ''.join(difflib.unified_diff(old.splitlines(keepends=True), new.splitlines(keepends=True),
                                         fromfile='frozen-V7-runner', tofile='derived-V8-runner'))
    dst.write_bytes(raw)
    shutil.copymode(src, dst)
    diff.write_text(patch, encoding='utf-8')
    print(json.dumps({'v7_blob': V7_BLOB, 'v8_blob': git_blob(raw),
                      'replacements': len(REPLACEMENTS), 'diff_sha256': hashlib.sha256(patch.encode()).hexdigest()},
                     sort_keys=True))


if __name__ == '__main__':
    main()
