name: upstream

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  legacy:
    runs-on: ubuntu-latest
    steps:
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y yosys z3 git make
          yosys -V
          z3 --version
      - name: Checkout upstream
        run: |
          git clone https://github.com/ZipCPU/zipcpu.git /tmp/upstream
      - name: Probe R0
        run: |
          cd /tmp/upstream
          git checkout 128cab89f5edaae4699184f50c1334598ebe904e
          make -C bench/formal clean >/dev/null 2>&1 || true
          make -C bench/formal pipemem SOLVER='-s z3'
      - name: Probe R1
        run: |
          cd /tmp/upstream
          git checkout d511239e19be8fcc7f340a64554ea93699637e62
          make -C bench/formal clean >/dev/null 2>&1 || true
          make -C bench/formal pipemem SOLVER='-s z3'
